image: gitpod/workspace-postgres

tasks:
  - name: Redis
    init: docker run -d --name redis -p 6379:6379 redis:7-alpine
    
  - name: Setup
    init: |
      # Install dependencies
      bundle install
      pnpm install
      
      # Setup database
      cp config/database.yml.development-sample config/database.yml
      bin/rails db:create db:migrate
      
      # Create admin user
      bin/rails "admin:create[admin@localhost.com,password,admin]"
    command: |
      # Start Rails server
      bin/rails server -b 0.0.0.0

  - name: Ember
    command: bin/ember-cli server --host 0.0.0.0
    
  - name: Sidekiq
    command: bin/sidekiq

ports:
  - port: 3000
    onOpen: ignore
  - port: 4200
    onOpen: open-browser
    visibility: public
  - port: 1080
    onOpen: ignore

vscode:
  extensions:
    - rebornix.ruby
    - castwide.solargraph
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode